#!/usr/bin/env bash
set -eo pipefail

echo "=== EAS pre-install: fixing pnpm version compatibility ==="

# Activate corepack so the packageManager field in package.json is respected
# This upgrades EAS's default pnpm to pnpm@10.26.1 which generated the lockfile
corepack enable
corepack prepare pnpm@10.26.1 --activate

echo "Active pnpm version: $(pnpm --version)"

# Remove the old lockfile — it was generated by pnpm 10 but EAS shipped
# an older pnpm that reports it as incompatible. After upgrading via corepack
# we regenerate a fresh one so the subsequent --frozen-lockfile step succeeds.
if [ -f pnpm-lock.yaml ]; then
  echo "Removing incompatible lockfile..."
  rm -f pnpm-lock.yaml
fi

echo "Generating fresh lockfile with pnpm $(pnpm --version)..."
pnpm install --no-frozen-lockfile

echo "=== pre-install complete ==="
