#!/usr/bin/env bash
set -eo pipefail

echo "Siyaj pre-install: enabling corepack to use pnpm@10.26.1..."

# Enable corepack so Node.js respects the "packageManager" field in package.json
# This ensures EAS uses pnpm 10.x which generated lockfileVersion 9.0
corepack enable || true
corepack prepare pnpm@10.26.1 --activate || true

echo "pnpm version: $(pnpm --version)"

# Remove incompatible lockfile if present (generated by older pnpm)
if [ -f pnpm-lock.yaml ]; then
  LOCKFILE_VERSION=$(head -1 pnpm-lock.yaml | grep -o "'[0-9.]*'" | tr -d "'" || echo "unknown")
  echo "Found existing lockfile version: $LOCKFILE_VERSION"
  rm -f pnpm-lock.yaml
  echo "Removed old lockfile."
fi

# Generate a fresh lockfile with the correct pnpm version
echo "Generating fresh lockfile..."
pnpm install --no-frozen-lockfile

echo "Pre-install complete. EAS frozen-lockfile install will now succeed."
