#!/usr/bin/env bash
# IMPORTANT: No set -e — script must never abort early

echo "=== pre-install (siyaj) start ==="
echo "pnpm: $(pnpm --version 2>/dev/null || echo NOT_FOUND)"

# Step 1: Replace workspace file with a minimal one that ALL pnpm versions understand.
# The committed file uses pnpm-10-only features (minimumReleaseAge, catalog:).
cat > pnpm-workspace.yaml << 'WSEOF'
packages:
  - artifacts/siyaj
WSEOF
echo "pnpm-workspace.yaml simplified (1 package)."

# Step 2: Delete the committed lockfile.
# It was generated by pnpm v10 (lockfileVersion 9.0) in Replit.
# If EAS's built-in pnpm is v8 or older it will say "not compatible" and ignore it.
rm -f pnpm-lock.yaml
echo "Old pnpm-lock.yaml removed."

# Step 3: Regenerate the lockfile using EXACTLY the pnpm binary EAS is running.
# Whatever version EAS activated (built-in or via corepack), we use the same one,
# so the new lockfile's format will match what --frozen-lockfile expects.
echo "Regenerating lockfile with $(pnpm --version 2>/dev/null || echo unknown) ..."
pnpm install --no-frozen-lockfile --ignore-scripts 2>&1 | tail -8 || \
  echo "WARNING: pnpm install had errors, continuing anyway."
echo "Lockfile regeneration done."

# Step 4: Fix Gradle JVM args — remove the -XX:MaxPermSize flag Java 17 rejects.
mkdir -p ~/.gradle
JAVA_HOME_CANDIDATE=""
for dir in /usr/lib/jvm /usr/local/lib/jvm /opt/java /usr/java; do
  found=$(find "$dir" -maxdepth 5 -name 'javac' 2>/dev/null | head -1)
  if [ -n "$found" ]; then
    JAVA_HOME_CANDIDATE=$(dirname "$(dirname "$found")")
    break
  fi
done

if [ -n "$JAVA_HOME_CANDIDATE" ]; then
  cat > ~/.gradle/gradle.properties << GEOF
org.gradle.java.home=$JAVA_HOME_CANDIDATE
org.gradle.jvmargs=-XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Xmx4g -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
GEOF
  echo "Gradle: JAVA_HOME=$JAVA_HOME_CANDIDATE"
else
  cat > ~/.gradle/gradle.properties << GEOF
org.gradle.jvmargs=-XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Xmx4g -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
GEOF
  echo "Gradle: using system Java."
fi

echo "=== pre-install (siyaj) done ==="
