#!/usr/bin/env bash
# No set -e — handle errors gracefully so the script never aborts early

echo "=== EAS pre-install (siyaj): start ==="

# ── 1. Use whatever pnpm EAS already has (corepack / built-in).
#        Do NOT install a new pnpm — that risks generating a lockfile
#        in a different format than what EAS will later use for --frozen-lockfile.
echo "pnpm version: $(pnpm --version 2>/dev/null || echo 'not found')"

# ── 2. Replace the workspace file.
#        The repo's pnpm-workspace.yaml uses pnpm-10-only features
#        (minimumReleaseAge, catalog:) that older pnpm versions reject.
#        We swap it for a minimal file that every pnpm version understands.
cat > pnpm-workspace.yaml << 'WSEOF'
packages:
  - artifacts/siyaj
WSEOF
echo "Simplified pnpm-workspace.yaml written."

# ── 3. Remove the committed lockfile.
#        It was generated by the Replit environment's pnpm version, which may
#        differ from the one EAS is actually running.  We regenerate below.
rm -f pnpm-lock.yaml
echo "Old pnpm-lock.yaml removed."

# ── 4. Generate a fresh lockfile with the SAME pnpm EAS will use for install.
#        This guarantees format compatibility when EAS later runs
#        "pnpm install --frozen-lockfile".
echo "Regenerating pnpm-lock.yaml..."
pnpm install --no-frozen-lockfile --ignore-scripts 2>&1 | tail -5
echo "pnpm-lock.yaml regenerated."

# ── 5. Fix Gradle JVM args (remove invalid -XX:MaxPermSize that Java 17 rejects).
mkdir -p ~/.gradle

JAVA_HOME_CANDIDATE=""
for dir in /usr/lib/jvm /usr/local/lib/jvm; do
  found=$(find "$dir" -maxdepth 4 -name 'javac' 2>/dev/null | head -1)
  if [ -n "$found" ]; then
    JAVA_HOME_CANDIDATE=$(dirname "$(dirname "$found")")
    break
  fi
done

if [ -n "$JAVA_HOME_CANDIDATE" ]; then
  cat > ~/.gradle/gradle.properties << GEOF
org.gradle.java.home=$JAVA_HOME_CANDIDATE
org.gradle.jvmargs=-XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Xmx4g -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
GEOF
  echo "Gradle properties written (JAVA_HOME=$JAVA_HOME_CANDIDATE)."
else
  cat > ~/.gradle/gradle.properties << GEOF
org.gradle.jvmargs=-XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Xmx4g -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
GEOF
  echo "Gradle properties written (system Java)."
fi

echo "=== EAS pre-install (siyaj): done ==="
